version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb  
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  my-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
